[package]
name = "weave-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Domain models and core traits for Weave"

[dependencies]
serde = { workspace = true }
sha1 = "0.10.6"
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
